# Import libraries

In [1]:
import os
import numpy as np
import pandas as pd
from joblib import Parallel, delayed
from tqdm.notebook import tqdm
import warnings
warnings.filterwarnings("ignore", category=pd.errors.SettingWithCopyWarning)

# Read data

In [2]:
folder = os.path.join('..', 'dataset-documentation', 'raw_data')

In [9]:
data_18augsep = pd.read_csv(
    os.path.join(
        folder,
        'MBTA Bus Arrival Departure Times 2019',
        'MBTA Bus Arrival Departure Jan-Mar 2019.csv'
    )
)

In [5]:
data_18augsep.head().to_csv("./presentation/origin_arrdep.csv", index = False)

# Data cleaning

## drop 'earliness' variable & missing values

In [10]:
if 'earliness' in data_18augsep.columns:
    data_18augsep = data_18augsep.drop('earliness', axis = 1)

In [11]:
data_18augsep.isna().sum() / data_18augsep.shape[0]

service_date         0.000000
route_id             0.000000
direction            0.000000
half_trip_id         0.000021
stop_id              0.000000
time_point_id        0.000225
time_point_order     0.000225
point_type           0.000000
standard_type        0.000000
scheduled            0.000000
actual               0.063560
scheduled_headway    0.504160
headway              0.573335
dtype: float64

In [6]:
## 'half_trip_id' missing values (0.0030%)
data_18augsep = data_18augsep.dropna(subset=['half_trip_id'])

In [7]:
## 'time_point_id' & 'time_point_order' missing values (0.0234%)
## We can use others years data to interpolate, but the time_point_order might be different. 
## So we just drop the missing vaue
data_18augsep = data_18augsep.dropna(subset=['time_point_id', 'time_point_order'])

In [8]:
## 'actual' missing values (7.0866%)
data_18augsep = data_18augsep.dropna(subset=['actual'])

In [13]:
## 'headway' should not have missing value if the 'standard_type' is 'Headway', however, we found there are many reason will cause the headway missing.
## so we just keep the missing values first
num = data_18augsep.query("standard_type == 'Headway'")['headway'].isna().sum()
print(f'Num of Headway missing values, when standard_type is Headway: {num}')

Num of Headway missing values, when standard_type is Headway: 166320

In [14]:
data_18augsep = data_18augsep.reset_index(drop=True)

## Missing values

In [15]:
data_18augsep.isna().sum() / data_18augsep.shape[0]

service_date         0.000000
route_id             0.000000
direction            0.000000
half_trip_id         0.000000
stop_id              0.000000
time_point_id        0.000000
time_point_order     0.000000
point_type           0.000000
standard_type        0.000000
scheduled            0.000000
actual               0.000000
earliness            0.485503
scheduled_headway    0.514497
headway              0.549484
dtype: float64

## reformat 'service_date' variable

In [17]:
# keep Year-Month-Day
data_18augsep['service_date'] = pd.to_datetime(data_18augsep['service_date'].str.slice(0, 10))

In [18]:
scheduled_is_next_day = (data_18augsep['actual'].notna() & data_18augsep['scheduled'].str.startswith('1900-01-02')).astype(int)
actual_is_next_day =  (data_18augsep['actual'].notna() & data_18augsep['actual'].str.startswith('1900-01-02')).astype(int) # true -> if start_with 01-02, else start_with 01-01 or na

In [19]:
## reformat scheduled & actual variables
data_18augsep['scheduled'] = pd.to_datetime(data_18augsep['scheduled'], format = '%Y-%m-%dT%H:%M:%SZ')
data_18augsep['scheduled'] = data_18augsep['scheduled'].dt.strftime('%H:%M:%S')
data_18augsep['scheduled'] = pd.to_datetime(data_18augsep['scheduled'], format='%H:%M:%S').dt.time.astype(str)
data_18augsep['scheduled_datetime'] = pd.to_datetime(data_18augsep['service_date'].astype(str) + ' ' + data_18augsep['scheduled'])
timedelta_adjustment = pd.to_timedelta(scheduled_is_next_day, unit='d')
data_18augsep['scheduled_datetime'] += timedelta_adjustment

In [20]:
data_18augsep['actual'] = pd.to_datetime(data_18augsep['actual'], format = '%Y-%m-%dT%H:%M:%SZ')
data_18augsep['actual'] = data_18augsep['actual'].dt.strftime('%H:%M:%S')
data_18augsep['actual'] = pd.to_datetime(data_18augsep['actual'], format='%H:%M:%S').dt.time.astype(str)
data_18augsep['actual_datetime'] = pd.to_datetime(data_18augsep['service_date'].astype(str) + ' ' + data_18augsep['actual'])
timedelta_adjustment = pd.to_timedelta(actual_is_next_day, unit='d')
data_18augsep['actual_datetime'] += timedelta_adjustment

In [21]:
data_18augsep.head()

,service_date,route_id,direction,half_trip_id,stop_id,time_point_id,time_point_order,point_type,standard_type,scheduled,actual,scheduled_headway,headway,scheduled_datetime,actual_datetime
0,2018-08-01,01,Inbound,40121394.0,75,mit,4.0,Midpoint,Schedule,05:19:00,05:19:34,NaN,NaN,2018-08-01 05:19:00,2018-08-01 05:19:34
1,2018-08-01,01,Inbound,40121394.0,79,hynes,5.0,Midpoint,Schedule,05:22:00,05:23:20,NaN,NaN,2018-08-01 05:22:00,2018-08-01 05:23:20
2,2018-08-01,01,Inbound,40121394.0,187,masta,6.0,Midpoint,Schedule,05:25:00,05:25:58,NaN,NaN,2018-08-01 05:25:00,2018-08-01 05:25:58
3,2018-08-01,01,Inbound,40121394.0,59,Wasma,7.0,Midpoint,Schedule,05:28:00,05:28:26,NaN,NaN,2018-08-01 05:28:00,2018-08-01 05:28:26
4,2018-08-01,01,Inbound,40121565.0,110,hhgat,1.0,Startpoint,Headway,05:30:00,05:29:57,1200.0,1218.0,2018-08-01 05:30:00,2018-08-01 05:29:57

In [2]:
# data cleaning pipeline
def clean_data(df):
    if 'earliness' in df.columns:
        df = df.drop('earliness', axis = 1)
    df['service_date'] = pd.to_datetime(df['service_date'])
    df['service_date'] = df['service_date'].apply(lambda x: x.strftime('%Y-%m-%d')) 

    df['scheduled'] = pd.to_datetime(df['scheduled'])
    df['scheduled_nextday'] = df['scheduled'].apply(lambda x: x.strftime('%m-%d') == '01-02')
    df['scheduled'] = df['scheduled'].apply(lambda x: x.strftime('%H:%M:%S') if pd.notnull(x) else x)
    df['actual'] = pd.to_datetime(df['actual'])
    df['actual_nextday'] = df['actual'].apply(lambda x: x.strftime('%m-%d') == '01-02')
    df['actual'] = df['actual'].apply(lambda x: x.strftime('%H:%M:%S') if pd.notnull(x) else x)

    df = df.dropna(subset=['half_trip_id', 'time_point_id', 'time_point_order', 'actual'])
    return df

In [24]:
data_18augsep.to_csv('arrdep_18augsep_simplecleaned.csv', index=False)

In [4]:
data = pd.read_csv("./old_version//cleaned_2019-01-03_data.csv")

In [11]:
data.iloc[:10000 :].query("route_id == '111'").sort_values(["service_date", "route_id", "direction", "time_point_order", "stop_id", "scheduled"]).to_csv("test2.csv", index = False)

Empty DataFrame
Columns: [service_date, route_id, direction, half_trip_id, stop_id, time_point_id, time_point_order, point_type, standard_type, scheduled, actual, scheduled_headway, headway, scheduled_datetime, actual_datetime, available_bus_depart_time]
Index: []

In [14]:
data.iloc[:10000, :].to_csv("test3.csv", index = False)

In [12]:
df = pd.read_csv("./arrdep_2019-Jan-Mar_simplecleaned.csv")

In [20]:
df.query("service_date == '2019-01-01' and route_id == '111' and time_point_order == 2 and direction == 'Inbound'").drop(
    ['service_date' , 'stop_id', 'point_type', 'standard_type', 'scheduled_headway', 'headway', 'scheduled_datetime', 'actual_datetime']
, axis = 1).sort_values(['time_point_id', 'scheduled']).to_csv('./presentation/wrong_departure_order.csv', index = False)

In [18]:
data.query("half_trip_id == 41928289.0").sort_values("time_point_order")

,service_date,route_id,direction,half_trip_id,stop_id,time_point_id,time_point_order,point_type,standard_type,scheduled,actual,scheduled_headway,headway,scheduled_datetime,actual_datetime,available_bus_depart_time
256,2019-01-01,111,Inbound,41928289.0,5547,woodc,1.0,Startpoint,Headway,08:42:00,08:42:21,960.0,972.0,2019-01-01 08:42:00,2019-01-01 08:42:21,2019-01-01 08:42:21
567,2019-01-01,111,Inbound,41928289.0,5592,garfi,2.0,Midpoint,Headway,08:45:00,08:45:17,960.0,995.0,2019-01-01 08:45:00,2019-01-01 08:45:17,2019-01-01 08:45:17
630,2019-01-01,111,Inbound,41928289.0,5595,smore,3.0,Midpoint,Headway,08:47:00,08:47:19,960.0,984.0,2019-01-01 08:47:00,2019-01-01 08:47:19,2019-01-01 08:47:19
950,2019-01-01,111,Inbound,41928289.0,5601,wacry,4.0,Midpoint,Headway,08:51:00,08:51:20,360.0,406.0,2019-01-01 08:51:00,2019-01-01 08:51:20,2019-01-01 08:51:20
22,2019-01-01,111,Inbound,41928289.0,5605,belsq,5.0,Midpoint,Headway,08:55:00,08:53:37,360.0,435.0,2019-01-01 08:55:00,2019-01-01 08:53:37,2019-01-01 09:05:20
144,2019-01-01,111,Inbound,41928289.0,5607,thche,6.0,Midpoint,Headway,08:57:00,08:55:16,360.0,432.0,2019-01-01 08:57:00,2019-01-01 08:55:16,2019-01-01 09:07:05
330,2019-01-01,111,Inbound,41928289.0,12001,tobin,7.0,Midpoint,Headway,08:59:00,08:56:42,360.0,438.0,2019-01-01 08:59:00,2019-01-01 08:56:42,2019-01-01 09:08:20
454,2019-01-01,111,Inbound,41928289.0,12003,ruthf,8.0,Midpoint,Headway,09:00:00,08:59:59,360.0,498.0,2019-01-01 09:00:00,2019-01-01 08:59:59,2019-01-01 09:10:24
704,2019-01-01,111,Inbound,41928289.0,2829,cacom,9.0,Midpoint,Headway,09:02:00,09:01:39,360.0,523.0,2019-01-01 09:02:00,2019-01-01 09:01:39,2019-01-01 09:11:52
828,2019-01-01,111,Inbound,41928289.0,8310,hayms,10.0,Endpoint,Headway,09:03:00,09:01:45,360.0,477.0,2019-01-01 09:03:00,2019-01-01 09:01:45,2019-01-01 09:11:56

In [19]:
data.query("half_trip_id == 41928261.0").sort_values("time_point_order")

,service_date,route_id,direction,half_trip_id,stop_id,time_point_id,time_point_order,point_type,standard_type,scheduled,actual,scheduled_headway,headway,scheduled_datetime,actual_datetime,available_bus_depart_time
951,2019-01-01,111,Inbound,41928261.0,5601,wacry,1.0,Startpoint,Headway,09:01:00,09:01:17,600.0,597.0,2019-01-01 09:01:00,2019-01-01 09:01:17,2019-01-01 09:01:17
23,2019-01-01,111,Inbound,41928261.0,5605,belsq,2.0,Midpoint,Headway,09:05:00,09:05:20,600.0,703.0,2019-01-01 09:05:00,2019-01-01 09:05:20,2019-01-01 09:05:20
145,2019-01-01,111,Inbound,41928261.0,5607,thche,3.0,Midpoint,Headway,09:07:00,09:07:05,600.0,709.0,2019-01-01 09:07:00,2019-01-01 09:07:05,2019-01-01 09:07:05
331,2019-01-01,111,Inbound,41928261.0,12001,tobin,4.0,Midpoint,Headway,09:09:00,09:08:20,600.0,698.0,2019-01-01 09:09:00,2019-01-01 09:08:20,2019-01-01 09:16:16
455,2019-01-01,111,Inbound,41928261.0,12003,ruthf,5.0,Midpoint,Headway,09:10:00,09:10:24,600.0,625.0,2019-01-01 09:10:00,2019-01-01 09:10:24,2019-01-01 09:10:24
705,2019-01-01,111,Inbound,41928261.0,2829,cacom,6.0,Midpoint,Headway,09:12:00,09:11:52,600.0,613.0,2019-01-01 09:12:00,2019-01-01 09:11:52,2019-01-01 09:19:19
829,2019-01-01,111,Inbound,41928261.0,8310,hayms,7.0,Endpoint,Headway,09:13:00,09:11:56,600.0,611.0,2019-01-01 09:13:00,2019-01-01 09:11:56,2019-01-01 09:19:47