In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../dataset-documentation/cleaned_data/arrival_depart_cleaned_data/cleaned_2022-01_data.csv")

In [34]:
def get_mean_interval(df):
    df["actual_datetime"] = pd.to_datetime(df["actual_datetime"])
    df['time_interval'] = df.groupby(['service_date', 'route_id', 'direction_id', 'stop_id'])['actual_datetime'].diff().dt.total_seconds()

    ret = df.groupby('stop_id', as_index=False).agg(mean_headway=("time_interval", "mean"), median_headway=("time_interval", "median"))

    return ret

In [35]:
t = get_mean_interval(df)

In [42]:
df.groupby("stop_id", as_index=False)["scheduled_headway"].nunique()

     stop_id  scheduled_headway
0         13                  3
1        185                  0
2        322                  1
3        323                 38
4        334                 56
..       ...                ...
146    41187                  6
147    64000                 58
148    67120                  0
149    85568                  0
150    96459                  0

[151 rows x 2 columns]

In [46]:
df["headway_latency"] = df["time_interval"] - df["scheduled_headway"]

In [53]:
df.groupby("stop_id", as_index=False)["headway_latency"].median().sort_values("headway_latency", ascending=False).to_csv("./test.csv", index=False)

In [61]:
df.query("stop_id == 185 and direction_id == 'Inbound'").sort_values("actual_datetime").head(30)

,service_date,route_id,direction_id,half_trip_id,stop_id,time_point_id,time_point_order,point_type,standard_type,scheduled,actual,scheduled_headway,headway,scheduled_datetime,actual_datetime,available_bus_depart_time,time_interval,headway_latency
5794,2022-01-01,24,Inbound,54136538.0,185,matpn,4,Midpoint,Schedule,09:47:00,09:45:58,NaN,NaN,2022-01-01 09:47:00,2022-01-01 09:45:58,2022-01-01 10:53:19,NaN,NaN
5795,2022-01-01,24,Inbound,54136540.0,185,matpn,4,Midpoint,Schedule,10:53:00,10:53:19,NaN,NaN,2022-01-01 10:53:00,2022-01-01 10:53:19,2022-01-01 10:53:19,4041.0,NaN
5796,2022-01-01,24,Inbound,54136542.0,185,matpn,4,Midpoint,Schedule,11:58:00,11:56:30,NaN,NaN,2022-01-01 11:58:00,2022-01-01 11:56:30,2022-01-01 13:02:39,3791.0,NaN
5797,2022-01-01,24,Inbound,54136544.0,185,matpn,4,Midpoint,Schedule,13:03:00,13:02:39,NaN,NaN,2022-01-01 13:03:00,2022-01-01 13:02:39,2022-01-01 14:10:53,3969.0,NaN
5798,2022-01-01,24,Inbound,54136547.0,185,matpn,4,Midpoint,Schedule,14:07:00,14:10:53,NaN,NaN,2022-01-01 14:07:00,2022-01-01 14:10:53,2022-01-01 14:10:53,4094.0,NaN
5799,2022-01-01,24,Inbound,54136559.0,185,matpn,4,Midpoint,Schedule,15:15:00,15:17:24,NaN,NaN,2022-01-01 15:15:00,2022-01-01 15:17:24,2022-01-01 15:17:24,3991.0,NaN
5800,2022-01-01,24,Inbound,54136561.0,185,matpn,4,Midpoint,Schedule,16:17:00,16:18:57,NaN,NaN,2022-01-01 16:17:00,2022-01-01 16:18:57,2022-01-01 16:18:57,3693.0,NaN
5801,2022-01-01,24,Inbound,54136549.0,185,matpn,4,Midpoint,Schedule,17:22:00,17:28:28,NaN,NaN,2022-01-01 17:22:00,2022-01-01 17:28:28,2022-01-01 17:28:28,4171.0,NaN
5802,2022-01-01,24,Inbound,54136551.0,185,matpn,4,Midpoint,Schedule,18:26:00,18:28:59,NaN,NaN,2022-01-01 18:26:00,2022-01-01 18:28:59,2022-01-01 18:28:59,3631.0,NaN
5803,2022-01-01,24,Inbound,54136553.0,185,matpn,4,Midpoint,Schedule,19:31:00,19:31:25,NaN,NaN,2022-01-01 19:31:00,2022-01-01 19:31:25,2022-01-01 19:31:25,3746.0,NaN
5804,2022-01-01,24,Inbound,54136555.0,185,matpn,4,Midpoint,Schedule,20:36:00,20:37:13,NaN,NaN,2022-01-01 20:36:00,2022-01-01 20:37:13,2022-01-01 20:37:13,3948.0,NaN
5805,2022-01-01,24,Inbound,54136557.0,185,matpn,4,Midpoint,Schedule,21:40:00,21:42:57,NaN,NaN,2022-01-01 21:40:00,2022-01-01 21:42:57,2022-01-01 21:42:57,3944.0,NaN
14639,2022-01-02,24,Inbound,54142448.0,185,matpn,4,Midpoint,Schedule,09:47:00,09:49:21,NaN,NaN,2022-01-02 09:47:00,2022-01-02 09:49:21,2022-01-02 09:49:21,NaN,NaN
14640,2022-01-02,24,Inbound,54142450.0,185,matpn,4,Midpoint,Schedule,10:53:00,10:52:44,NaN,NaN,2022-01-02 10:53:00,2022-01-02 10:52:44,2022-01-02 11:59:15,3803.0,NaN
14641,2022-01-02,24,Inbound,54142452.0,185,matpn,4,Midpoint,Schedule,11:58:00,11:59:15,NaN,NaN,2022-01-02 11:58:00,2022-01-02 11:59:15,2022-01-02 11:59:15,3991.0,NaN
14642,2022-01-02,24,Inbound,54142454.0,185,matpn,4,Midpoint,Schedule,13:03:00,13:02:30,NaN,NaN,2022-01-02 13:03:00,2022-01-02 13:02:30,2022-01-02 14:07:16,3795.0,NaN
14643,2022-01-02,24,Inbound,54142457.0,185,matpn,4,Midpoint,Schedule,14:07:00,14:07:16,NaN,NaN,2022-01-02 14:07:00,2022-01-02 14:07:16,2022-01-02 14:07:16,3886.0,NaN
14644,2022-01-02,24,Inbound,54142469.0,185,matpn,4,Midpoint,Schedule,15:15:00,15:12:43,NaN,NaN,2022-01-02 15:15:00,2022-01-02 15:12:43,2022-01-02 16:16:22,3927.0,NaN
14645,2022-01-02,24,Inbound,54142471.0,185,matpn,4,Midpoint,Schedule,16:17:00,16:16:22,NaN,NaN,2022-01-02 16:17:00,2022-01-02 16:16:22,2022-01-02 17:23:22,3819.0,NaN
14646,2022-01-02,24,Inbound,54142459.0,185,matpn,4,Midpoint,Schedule,17:22:00,17:23:22,NaN,NaN,2022-01-02 17:22:00,2022-01-02 17:23:22,2022-01-02 17:23:22,4020.0,NaN
14647,2022-01-02,24,Inbound,54142461.0,185,matpn,4,Midpoint,Schedule,18:26:00,18:26:07,NaN,NaN,2022-01-02 18:26:00,2022-01-02 18:26:07,2022-01-02 18:26:07,3765.0,NaN
14648,2022-01-02,24,Inbound,54142463.0,185,matpn,4,Midpoint,Schedule,19:31:00,19:32:09,NaN,NaN,2022-01-02 19:31:00,2022-01-02 19:32:09,2022-01-02 19:32:09,3962.0,NaN
14649,2022-01-02,24,Inbound,54142465.0,185,matpn,4,Midpoint,Schedule,20:36:00,20:38:19,NaN,NaN,2022-01-02 20:36:00,2022-01-02 20:38:19,2022-01-02 20:38:19,3970.0,NaN
14650,2022-01-02,24,Inbound,54142467.0,185,matpn,4,Midpoint,Schedule,21:40:00,21:40:09,NaN,NaN,2022-01-02 21:40:00,2022-01-02 21:40:09,2022-01-02 21:40:09,3710.0,NaN
26629,2022-01-03,24,Inbound,54149272.0,185,matpn,4,Midpoint,Schedule,05:15:00,05:17:48,NaN,NaN,2022-01-03 05:15:00,2022-01-03 05:17:48,2022-01-03 05:17:48,NaN,NaN
26630,2022-01-03,24,Inbound,54149306.0,185,matpn,4,Midpoint,Schedule,05:40:00,05:52:21,NaN,NaN,2022-01-03 05:40:00,2022-01-03 05:52:21,2022-01-03 05:52:21,2073.0,NaN
33248,2022-01-03,33,Inbound,54150115.0,185,matpn,5,Endpoint,Schedule,06:09:00,06:08:24,NaN,NaN,2022-01-03 06:09:00,2022-01-03 06:08:24,2022-01-03 06:41:00,NaN,NaN
26631,2022-01-03,24,Inbound,54149274.0,185,matpn,4,Midpoint,Schedule,06:10:00,06:13:47,NaN,NaN,2022-01-03 06:10:00,2022-01-03 06:13:47,2022-01-03 06:13:47,1286.0,NaN
33249,2022-01-03,33,Inbound,54150133.0,185,matpn,5,Endpoint,Schedule,06:40:00,06:41:00,NaN,NaN,2022-01-03 06:40:00,2022-01-03 06:41:00,2022-01-03 06:41:00,1956.0,NaN
26632,2022-01-03,24,Inbound,54149308.0,185,matpn,4,Midpoint,Schedule,06:45:00,06:49:02,NaN,NaN,2022-01-03 06:45:00,2022-01-03 06:49:02,2022-01-03 06:49:02,2115.0,NaN

In [58]:
df.query("route_id == 24").sort_values("actual_datetime").head(200).to_csv("./test2.csv", index=False)